services:
  - type: web
    name: nea-bot
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev libavfilter-dev libswresample-dev
      pip install -r requirements.txt
    startCommand: python neamain.py
    env: python
